import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv('netflix_titles.csv')
data = data.dropna(subset=['type','release_year','rating','country','duration'])
types = data['type'].value_counts()
plt.figure(figsize=(6,4))
plt.bar(types.index, types.values, color=["skyblue","orange"])
plt.title('Number of Movies shows vs Tv shows on netflix')
plt.xlabel('Type')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig('Movies_vs_Tvshpws.png')
plt.show()
rating = data['rating'].value_counts()
plt.figure(figsize=(6,4))
plt.pie(rating,labels=rating.index, autopct='%1.1f%%')
plt.title('Percentage of Content Rating')
plt.savefig('Content_Rating.png')
plt.show()
release_year = data['release_year'].value_counts().sort_index()
plt.figure(figsize=(10,6))
plt.scatter(release_year.index,release_year.values, color='red')
plt.title('Release year vs Number of shows')
plt.xlabel('Release Year')
plt.ylabel('Number of Shows')
plt.tight_layout()
plt.grid(color='grey')
plt.savefig('Releaseyear_vs_Numberofshows.png')
plt.show()
country = data['country'].value_counts().head(10)
plt.figure(figsize=(8,6))
plt.barh(country.index,country.values,color='teal')
plt.title('Top 10 Countries by number of shows')
plt.xlabel('No. Of Shows')
plt.ylabel('Countries')
plt.tight_layout()
plt.savefig('Top 10 countries with respect of shows.png')
plt.show()
